### ISSUE TITLE
tcp server and multiplayer support?

### ISSUE THREAD

**Issue by shapr** [cdsmith/ourmud#3]

**Comment by cdsmith** [comment]
There are a few ways we could do this:

1. Just open a socket and do reads and writes to the socket instead of stdio.  You could connect with a telnet client, since telnet clients basically work as bare TCP communication as long as you don't send `\\xFF` characters.
2. Use a more full-featured telnet server, such as https://hackage.haskell.org/package/libtelnet, which might let us do a better job of handling buffering and such?  Maybe even discover the terminal capabilities of the client and use colors or other advanced features.
3. Write our own client.  That client could communicate over any protocol of our choice.  It could be anything from pure command line to a GUI app, and HTML page with JavaScript, or whatever else.

I like the idea of separating the core logic from the client interface, so that there could be multiple protocols and multiple clients implemented for the same world.  We could even have progressive features, like images associated with rooms. characters, or items, which would be shown only if the client has the ability to display them.

**Comment by cdsmith** [comment]
Of course, the above shouldn't stand in the way of getting something working!  I'll try to do a quick and dirty implementation with TCP sockets first.
